version: '3.8'

services:
  db:
    image: mongo:6.0
    container_name: db
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db:ro

  s3:
    image: minio/minio:RELEASE.2024-01-11T06-21-14Z
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - s3_data:/data:ro

  app:
    build:
      context: ./backend/video_hosting
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
      - s3

  vue-dev:
    build:
      context: ./frontend/videohost
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./frontend/videohost:/app:ro
      - /app/node_modules:ro
    environment:
      - NODE_ENV=development
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5173" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - app

volumes:
  mongo_data:
  s3_data:
