version: '3.8'

services:
  db:
    image: mongo:8.0
    container_name: db
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db

  s3:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - s3_data:/data

  app:
    build:
      context: ./backend/video_hosting
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
      - s3

  frontend:
    build:
      context: ./frontend/videohost
      dockerfile: Dockerfile
    container_name: client
    networks:
      - neo4j_network
    ports:
      - "127.0.0.1:3000:5173"
    depends_on:
      - app

volumes:
  mongo_data:  # For MongoDB
  s3_data:     # For MinIO
  node_modules: # For frontend node_modules
