version: '3.8'

services:
  db:
    image: mongo:6.0
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  s3:
    image: minio/minio:RELEASE.2024-01-11T06-21-14Z
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - s3_data:/data

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - s3

volumes:
  mongo_data:
  s3_data:
